title: Plague
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal Trash Bin. Have a look. take what you need ;) and leave what is useless..
  your welcome
    -Pl4gue
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pl4gue.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Pl4gue
tagline: Student
about-description: # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: coming@soon.com # Add your Email address
phone:  46 55 43 4b 20 59 4f 55  # Add your Phone number
website: https://pl4gue.github.io/ # Add your website, do not add http://
github: pl4gue # Add your Github handle
twitter: '@XXX' # Add your Twitter handle

# Tracker
analytics: UA-124104970-1

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
